version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: school-library_db
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: kapitonov
    ports:
      - "5437:5432"