// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBook(arg1) {
  return window['go']['transport']['Transport']['CreateBook'](arg1);
}

export function CreateStudent(arg1) {
  return window['go']['transport']['Transport']['CreateStudent'](arg1);
}

export function DeleteBook(arg1) {
  return window['go']['transport']['Transport']['DeleteBook'](arg1);
}

export function DeleteStudent(arg1) {
  return window['go']['transport']['Transport']['DeleteStudent'](arg1);
}

export function GetAllBooks() {
  return window['go']['transport']['Transport']['GetAllBooks']();
}

export function GetAllStudents() {
  return window['go']['transport']['Transport']['GetAllStudents']();
}

export function GetBookByID(arg1) {
  return window['go']['transport']['Transport']['GetBookByID'](arg1);
}

export function GetStudentByID(arg1) {
  return window['go']['transport']['Transport']['GetStudentByID'](arg1);
}

export function UpdateBook(arg1) {
  return window['go']['transport']['Transport']['UpdateBook'](arg1);
}

export function UpdateStudent(arg1) {
  return window['go']['transport']['Transport']['UpdateStudent'](arg1);
}
